// Code generated by MockGen. DO NOT EDIT.
// Source: internal/common/domain/rest_client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRestClient is a mock of RestClient interface.
type MockRestClient struct {
	ctrl     *gomock.Controller
	recorder *MockRestClientMockRecorder
}

// MockRestClientMockRecorder is the mock recorder for MockRestClient.
type MockRestClientMockRecorder struct {
	mock *MockRestClient
}

// NewMockRestClient creates a new mock instance.
func NewMockRestClient(ctrl *gomock.Controller) *MockRestClient {
	mock := &MockRestClient{ctrl: ctrl}
	mock.recorder = &MockRestClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestClient) EXPECT() *MockRestClientMockRecorder {
	return m.recorder
}

// DoGet mocks base method.
func (m *MockRestClient) DoGet(uri string, params map[string]string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoGet", uri, params)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoGet indicates an expected call of DoGet.
func (mr *MockRestClientMockRecorder) DoGet(uri, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoGet", reflect.TypeOf((*MockRestClient)(nil).DoGet), uri, params)
}

// DoPost mocks base method.
func (m *MockRestClient) DoPost(uri, params string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoPost", uri, params)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoPost indicates an expected call of DoPost.
func (mr *MockRestClientMockRecorder) DoPost(uri, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoPost", reflect.TypeOf((*MockRestClient)(nil).DoPost), uri, params)
}
